### ISSUE TITLE
Workflow and I/O understanding.

### ISSUE THREAD

**Issue by Tortoise17** [arturxe2/T-DEED_v2#2]
It is rather difficult to follow completely how here the I/O in this repo works. 

Normally, the video should export the frames, and than embeddings, from embeddings should the model interact and export the predictions. 

can you the sequence properly correct for me if I am wrong. Because for the inference, if I change the module to only_test as run, still it asks for frames_path.pkl. 
At which step it generates the frames_path.pkl file. 

Using extract_frames_sn.py and extract_frames_snb.py is also linked to soccernet dataset file structure(i guess).
Please if you could elaborate or provide any inference file for the customized video would be a great help.

**Comment by arturxe2** [comment]
Hi, I've updated the code so it no longer requires the frames-path.pkl file during inference. Since this repository is designed specifically for inference on the provided datasets, I recommend adapting the code to extract frames for your custom dataset, as well as modifying the ActionSpotVideoDataset class accordingly.

However, running train_tdeed.py still requires a labels file to evaluate the results. If you only want to perform inference, you can adapt the evaluate_tdeed_challenge.py file to work with your custom dataset.
